#!/usr/bin/env python3
"""Generate ProctorTokens.swift from the design of record.

PRO-0064. The mock's token block is the source; this is the only mechanism that
carries it into Swift. Nothing transcribes a value by hand, because nothing would
notice a transcription going stale and a token that disagrees with its source is
worse than an absent one: the app compiles, draws, and is wrong in a way no test
can see.

Follows gen-build-identity.sh's contract — argv is (output-dir, package-dir), and
it writes only when the content changes so an unchanged tree does not recompile
ProctorCore.

An unresolvable colour is a failure that names the token. An approximated colour
is precisely the defect class this repo's provenance thesis exists to prevent.
"""
import os
import re
import sys

SOURCE = "design/surfaces/parts/head.html"
VALID_TIERS = {"kit", "hig", "direction", "brand"}

HEX = re.compile(r"^#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6}|[0-9A-Fa-f]{8})$")
RGBA = re.compile(r"^rgba?\(\s*[\d.]+\s*,\s*[\d.]+\s*,\s*[\d.]+\s*(?:,\s*[\d.]+\s*)?\)$")
COLOUR_ISH = re.compile(r"#[0-9A-Fa-f]{3,8}|rgba?\(|color-mix\(|oklch\(|hsl\(")

DECL = re.compile(r"^\s*(--[a-z0-9-]+)\s*:\s*([^;]+);\s*/\*\s*tier:([a-z]+)\s*\*/")
DECL_UNTIERED = re.compile(r"^\s*(--[a-z0-9-]+)\s*:\s*([^;]+);")


def strip_at_rules(css):
    """Remove every @media / @supports region, braces balanced.

    The increased-contrast block redefines the same token names under
    `:root:not([data-appearance="dark"])` and `:root[data-appearance="dark"]`.
    Left in, those overrides are read as the palettes themselves — measured: the
    first version of this generator emitted `--accent` light as #EEC385, which is
    the increased-contrast *dark* value, and `--ink-2` light as a white alpha.
    Both compile and both are wrong, which is the failure this whole item exists
    to prevent.
    """
    out, i = [], 0
    while i < len(css):
        at = css.find("@", i)
        if at < 0:
            out.append(css[i:])
            break
        brace = css.find("{", at)
        if brace < 0:
            out.append(css[i:])
            break
        out.append(css[i:at])
        depth, j = 1, brace + 1
        while j < len(css) and depth:
            if css[j] == "{":
                depth += 1
            elif css[j] == "}":
                depth -= 1
            j += 1
        i = j
    return "".join(out)


def blocks(css):
    """The base :root block and the explicit dark one, matched exactly.

    Exactly, because `:root:not([data-appearance="dark"])` is not the light
    palette — it is an override of it.
    """
    css = strip_at_rules(css)
    out = {}
    for m in re.finditer(r"(?m)^(:root(?:\[data-appearance=\"dark\"\])?)\s*\{(.*?)\n\}", css, re.S):
        sel, body = m.group(1), m.group(2)
        if sel == ":root":
            out.setdefault("light", []).append(body)
        else:
            out.setdefault("dark", []).append(body)
    return out


def parse(body, where, errors):
    found = {}
    for line in body.split("\n"):
        m = DECL.match(line)
        if m:
            name, value, tier = m.group(1), m.group(2).strip(), m.group(3)
            if tier not in VALID_TIERS:
                errors.append(f"{name} in {where} carries tier '{tier}', which is not one of "
                              f"{sorted(VALID_TIERS)}")
                continue
            found[name] = (value, tier)
            continue
        u = DECL_UNTIERED.match(line)
        if u and "tier:" not in line:
            errors.append(f"{u.group(1)} in {where} has no tier. A cell you cannot tag is a "
                          f"value you invented — tag it {sorted(VALID_TIERS)}.")
    return found


def is_colour(value):
    return bool(COLOUR_ISH.search(value))


def resolvable(value):
    """A colour this generator will emit. Anything else fails by name."""
    v = value.strip()
    if HEX.match(v) or RGBA.match(v):
        return True
    return False


def swift_literal(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(tokens):
    lines = [
        "// Generated by scripts/gen-design-tokens.py from " + SOURCE + ".",
        "// Do not edit. Change the mock's token block and rebuild.",
        "//",
        "// The label ramp departs from Apple's kit deliberately, and the measurements are",
        "// here so the next person to 'correct' it reads them first: the kit's light",
        "// secondary tier at 50% measures 3.98:1 against white and cannot carry meaning,",
        "// and its tertiary at 25% measures 1.83:1 and can never carry text at all. This",
        "// design lifts secondary to 68% and tertiary to 56%, and keeps 25% for exactly the",
        "// two jobs the platform uses it for: dividers, and the disabled state.",
        "",
        "import Foundation",
        "",
        "public enum ProctorTokens {",
        "",
        "    public enum Appearance: String, Sendable, CaseIterable { case light, dark }",
        "",
        "    /// Where a value came from, which governs when it may change: a `direction`",
        "    /// token moves when the design moves, a `kit` token only when Apple's does.",
        "    public enum Tier: String, Sendable, CaseIterable { case kit, hig, direction, brand }",
        "",
        "    public struct Token: Sendable, Equatable {",
        "        public let name: String",
        "        public let light: String",
        "        public let dark: String?",
        "        public let tier: Tier",
        "        public let isColour: Bool",
        "    }",
        "",
        "    public static let all: [Token] = [",
    ]
    for name, (light, dark, tier, colour) in sorted(tokens.items()):
        d = swift_literal(dark) if dark is not None else "nil"
        lines.append(f"        Token(name: {swift_literal(name)}, light: {swift_literal(light)}, "
                     f"dark: {d}, tier: .{tier}, isColour: {'true' if colour else 'false'}),")
    lines += [
        "    ]",
        "",
        "    public static func token(_ name: String) -> Token? {",
        "        all.first { $0.name == name }",
        "    }",
        "",
        "    /// The value for an appearance. Dark falls back to light only where the design",
        "    /// authored no dark value — never by inverting one, because an inverted dark",
        "    /// scheme is how graphite becomes pure black.",
        "    public static func value(_ name: String, _ appearance: Appearance) -> String? {",
        "        guard let t = token(name) else { return nil }",
        "        return appearance == .dark ? (t.dark ?? t.light) : t.light",
        "    }",
        "",
        "    public static func accent(_ appearance: Appearance) -> String {",
        '        value("--accent", appearance) ?? ""',
        "    }",
        "",
        "    public static var colours: [Token] { all.filter(\\.isColour) }",
        "}",
        "",
    ]
    return "\n".join(lines)


def main():
    if len(sys.argv) < 3:
        sys.stderr.write("usage: gen-design-tokens.py <output-dir> <package-dir>\n")
        return 2
    out_dir, pkg_dir = sys.argv[1], sys.argv[2]
    src = os.path.join(pkg_dir, SOURCE)
    if not os.path.exists(src):
        sys.stderr.write(f"gen-design-tokens: {SOURCE} not found under {pkg_dir}\n")
        return 1

    css = open(src).read()
    b = blocks(css)
    errors = []
    light = {}
    for body in b.get("light", []):
        light.update(parse(body, ":root", errors))
    dark = {}
    for body in b.get("dark", []):
        dark.update(parse(body, ':root[data-appearance="dark"]', errors))

    tokens = {}
    for name, (value, tier) in light.items():
        colour = is_colour(value)
        if colour and not resolvable(value):
            errors.append(f"{name} = '{value}' is a colour this generator cannot resolve "
                          f"exactly. Give it a hex or rgba value, or teach the generator the "
                          f"form — never let it approximate.")
            continue
        d = dark.get(name, (None, None))[0]
        if d is not None and is_colour(d) and not resolvable(d):
            errors.append(f"{name} dark = '{d}' is a colour this generator cannot resolve.")
            continue
        tokens[name] = (value, d, tier, colour)

    if errors:
        for e in errors:
            sys.stderr.write("gen-design-tokens: " + e + "\n")
        return 1

    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, "ProctorTokens.swift")
    body = render(tokens)
    if os.path.exists(path) and open(path).read() == body:
        return 0                      # write-if-changed: no recompile downstream
    open(path, "w").write(body)
    return 0


if __name__ == "__main__":
    sys.exit(main())
